Repository ppp-team/my-pet-log, pull requests merged in 2024-02, with the labels that each got.

#52 [#51] feat : 내비게이션 바 구현
  app/create/(route)/pet-group/page.css.ts
  app/create/(route)/pet-group/page.tsx
  app/create/(route)/user-profile/page.css.ts
  app/create/(route)/user-profile/page.tsx
  app/select/page.tsx
  components/Home/HomePetProfile/HomePetProfile.tsx
  components/Layout/Mobile/FooterNavigationBar/FooterNavigationBar.css.ts
  components/Layout/Mobile/FooterNavigationBar/FooterNavigationBar.tsx
  components/Layout/Mobile/HeaderLogo/HeaderLogo.css.ts
  components/Layout/Mobile/HeaderLogo/HeaderLogo.tsx
  components/Layout/Mobile/HeaderPetGroup/HeaderPetGroup.css.ts
  components/Layout/Mobile/HeaderPetGroup/HeaderPetGroup.tsx
  components/Participate/ParticipatePetGroupModal.tsx
  components/types/petGroup.ts
Labels: 💫 feat

#55 [#50] feat : 육아일기 작성 Input
  app/diary/card/[cardid]/page.tsx
  app/diary/card/[cardid]/style.css.ts
  app/diary/detail/[_id]/page.tsx
  app/diary/detail/[_id]/style.css.ts
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  components/@common/SelectPet/index.tsx
  components/Diary/DateInput/index.tsx
  components/Diary/DiaryList/index.tsx
  components/Diary/ImageInput/index.tsx
  components/Diary/ImageInput/style.css.ts
  components/Diary/VideoInput/index.tsx
  components/Diary/VideoInput/style.css.ts
  styles/global.css.ts
  utils/datePrettier.ts
  utils/getPrettyToday.ts
Labels: 💫 feat, 🍀 refactor

#60 [#56] refactor : Sign폼 리팩토링
  app/login/page.css.ts
  app/login/page.tsx
  app/onboarding/page.tsx
  app/signup/page.css.ts
  app/signup/page.tsx
  assets/feather.svg
  assets/google.svg
  components/@common/SignButton/index.tsx
  components/@common/SignButton/style.css.ts
  components/Sign/AlertModal/styles.css.ts
  components/Sign/SignForm/SigninForm.tsx
  components/Sign/SignForm/SignupForm.tsx
  components/Sign/SignInput/Input.tsx
  components/Sign/SignInput/PasswordInput.tsx
Labels: 🍀 refactor

#44 [#43] feat : 계정관리(프로필, 비밀번호 변경) 페이지
  app/(settingsMenu)/(Account)/layout.css.ts
  app/(settingsMenu)/(Account)/layout.tsx
  app/(settingsMenu)/(Account)/password/page.tsx
  app/(settingsMenu)/(Account)/password/style.css.ts
  app/(settingsMenu)/(Account)/profile/page.tsx
  app/(settingsMenu)/(Account)/profile/style.css.ts
  app/(settingsMenu)/myprofile/page.tsx
  app/(settingsMenu)/received-invites/page.tsx
  app/healthlog/edit/page.tsx
  app/settings/@modal/(..)logout/page.tsx
  app/settings/page.tsx
  assets/no-profile.svg
  components/@common/Modal/style.css.ts
  components/Participate/ParticipatePetGroupForm.tsx
  components/Setting/Logout/index.tsx
  components/Setting/Logout/style.css.ts
  components/Setting/MyProfile/index.tsx
  components/Setting/MyProfile/mockData.json
  components/Setting/MyProfile/style.css.ts
  components/Setting/MypetCarousel/Card/index.tsx
  components/Setting/MypetCarousel/Card/style.css.ts
  components/Setting/MypetCarousel/index.tsx
  components/Setting/MypetCarousel/mockdata.json
  components/Setting/MypetCarousel/style.css.ts
  components/Sign/SignForm/SigninForm.tsx
  components/Sign/SignForm/SignupForm.tsx
  constants/inputConstant.ts
  styles/zindex.css.ts
Labels: 💫 feat, 🥹 incomplete

#59 [#57] refactor : 펫그룹 참여 폼 리팩토링
  components/Participate/ParticipatePetGroupForm.tsx
Labels: 🍀 refactor

#64 [#63] feat : 프로필 관리 페이지 구현, 비밀번호 변경 페이지 리팩토링
  app/(settingsMenu)/(Account)/password/page.tsx
  app/(settingsMenu)/(Account)/profile/page.tsx
  assets/no-profile.svg
Labels: 💫 feat, 🍀 refactor

#69 [#62] feat : 이미지 드래그앤드랍 기능
  app/diary/edit/page.tsx
  components/Diary/ImageInput/index.tsx
  components/Diary/ImageInput/style.css.ts
  package-lock.json
  package.json
Labels: 💫 feat

#68 [#61] feat : 에디터 드롭다운 & 퀵 버튼 기능 구현
  app/diary/edit/page.tsx
  app/healthlog/(route)/edit/page.css.ts
  app/healthlog/(route)/edit/page.tsx
  app/healthlog/edit/page.tsx
  assets/drop-down-icon.svg
  components/@common/DateInput/index.tsx
  components/Healthlog/EmptyHealthLog/index.tsx
  components/Healthlog/EmptyHealthLog/style.css.ts
  components/Healthlog/SearchLocation/index.tsx
  components/Healthlog/SearchLocation/style.css.ts
  components/Healthlog/SelectMateDropdown/index.tsx
  components/Healthlog/SelectMateDropdown/style.css.ts
  components/Healthlog/SubtypeDetail/index.tsx
  components/Healthlog/SubtypeDetail/style.css.ts
  components/Participate/ParticipatePetGroupForm.tsx
  public/data/subtypeOptions.ts
  styles/zindex.css.ts
Labels: 💫 feat

#71 [#65] feat : 루트 레이아웃
  app/layout.tsx
  app/select/page.tsx
  app/template.tsx
  components/Layout/AppLayout.tsx
  components/Layout/MainWrapper/MainWrapper.css.ts
  components/Layout/MainWrapper/MainWrapper.tsx
  components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.css.ts
  components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.tsx
  components/Layout/MobileHeaderLogo/MobileHeaderLogo.css.ts
  components/Layout/MobileHeaderLogo/MobileHeaderLogo.tsx
  components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  components/Layout/PcHeader/PcHeader.tsx
  constants/pagesWithHeader.ts
  styles/global.css.ts
Labels: 💫 feat

#75 [#74] feat : 간단한 모달 창 공통 컴포넌트 구현
  app/(settingsMenu)/(petmate)/member/page.tsx
  assets/close.svg
  components/@common/SimpleModal/index.tsx
  components/@common/SimpleModal/style.css.ts
Labels: 💫 feat

#79 [#78] feat : 펫메이트 초대 내역 페이지 구현
  app/(settingsMenu)/(petmate)/invitation/mockData.json
  app/(settingsMenu)/(petmate)/invitation/page.tsx
  app/(settingsMenu)/(petmate)/invitation/style.css.ts
  app/(settingsMenu)/(petmate)/layout.css.ts
  app/(settingsMenu)/(petmate)/layout.tsx
Labels: 💫 feat, 🎨 UI

#80 [#73] style : 육아일기 페이지 스타일링
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  app/diary/page.tsx
  app/diary/select/page.tsx
  assets/PlusIcon.tsx
  assets/add.svg
  assets/message.svg
  assets/search.svg
  assets/write.svg
  components/@common/SelectPet/index.tsx
  components/@common/SelectPet/style.css.ts
  components/Diary/DiaryList/index.tsx
  components/Diary/DiaryList/style.css.ts
  components/Diary/EmptyDiaryList/index.tsx
  components/Diary/EmptyDiaryList/style.css.ts
  components/Diary/EmptyDiaryList/style.ts
  components/Diary/ImageInput/style.css.ts
  components/Diary/VideoInput/index.tsx
  components/Diary/VideoInput/style.css.ts
Labels: 🎨 UI

#77 [#76] feat : 최초 유저 프로필 등록 페이지 (/create/user-profile)
  app/create/(route)/user-profile/page.tsx
  components/Participate/ParticipatePetGroupForm.tsx
  constants/inputConstant.ts
  utils/removeSpaces.ts
Labels: 💫 feat

#83 [#82] fix : 캘린더 닫을 시 날짜 반영 안 되는 이슈
  app/diary/edit/page.tsx
  components/@common/DateInput/index.tsx
Labels: 🛠️ fix

#87 [#81] feat : 건강수첩 메인 페이지 : 퀵버튼 및 세부 기능
  app/healthlog/edit/page.css.ts
  app/healthlog/edit/page.tsx
  app/healthlog/page.css.ts
  app/healthlog/page.tsx
  app/healthlog/select/page.tsx
  assets/feed-icon.svg
  assets/health-icon.svg
  assets/important-star-icon.svg
  assets/treat-icon.svg
  assets/walk-icon.svg
  assets/write-pencil-icon.svg
  components/@common/LogList/LogItem/index.tsx
  components/@common/LogList/LogItem/style.css.ts
  components/@common/LogList/index.tsx
  components/@common/LogList/sampleLogList.ts
  components/@common/LogList/style.css.ts
  components/Healthlog/LogDetail/index.tsx
  components/Healthlog/LogDetail/style.css.ts
  components/Healthlog/QuickButtons/index.tsx
  components/Healthlog/QuickButtons/style.css.ts
Labels: 💫 feat, 🍀 refactor, 🎨 UI

#98 chore : 컬러 상수값 추가
  styles/colors.css.ts
Labels: 🧹 chore

#93 [#92] feat : 초대받은 내역 페이지 구현(리뷰 부탁 >0<)
  app/(settingsMenu)/(petmate)/layout.tsx
  app/(settingsMenu)/received-invites/mockData.json
  app/(settingsMenu)/received-invites/page.css.ts
  app/(settingsMenu)/received-invites/page.tsx
  components/@common/TitleHeader/index.tsx
  components/@common/TitleHeader/style.css.ts
  package-lock.json
  package.json
  utils/getTimeAgo.ts
Labels: 💫 feat, 🎨 UI

#91 [#90] feat : 육아일기 상세페이지 구현
  app/diary/detail/[_id]/page.tsx
  app/diary/detail/[_id]/style.css.ts
  app/diary/detail/[_id]/swiper.css.ts
  assets/kebab.svg
  assets/like.svg
  assets/send.svg
  components/Diary/DiaryList/index.tsx
Labels: 💫 feat, 🎨 UI

#101 [#100] refactor : 모달 컴포넌트 이름 변경
  app/(settingsMenu)/(petmate)/member/page.tsx
  app/(settingsMenu)/logout/page.tsx
  app/select/page.tsx
  app/settings/@modal/(..)logout/page.tsx
  app/settings/@modal/default.tsx
  app/settings/layout.tsx
  components/@common/LogList/index.tsx
  components/@common/Modal/index.tsx
  components/@common/Modal/style.css.ts
  components/@common/ModalContainer/index.tsx
  components/@common/ModalContainer/style.css.ts
  components/@common/SimpleModal/index.tsx
  components/@common/SimpleModal/style.css.ts
  components/Diary/ImageInput/index.tsx
  components/Setting/Logout/index.tsx
  components/Setting/Logout/style.css.ts
  components/Sign/SignForm/SignupForm.tsx
Labels: 🛠️ fix, 🍀 refactor

#94 [#84] feat : 펫그룹 참여 모달 기획 수정안 반영, UI 스타일링
  app/select/page.tsx
  assets/caution.svg
  components/@common/InvitationForm/InvitationForm.css.ts
  components/@common/InvitationForm/InvitationForm.tsx
  components/Participate/ParticipatePetGroupForm.tsx
  components/Participate/ParticipatePetGroupModal.css.ts
  components/Participate/ParticipatePetGroupModal.tsx
  components/Participate/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  components/Participate/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  components/Participate/ReceivedInvitationList/ReceivedInvitationList.css.ts
  components/Participate/ReceivedInvitationList/ReceivedInvitationList.tsx
  components/types/petGroup.ts
  components/types/receivedInvitation.ts
  constants/inputConstant.ts
  package-lock.json
  package.json
  styles/global.css.ts
Labels: 💫 feat, 🎨 UI

#106 [design] 셋팅 페이지 디자인 1차
  app/settings/page.css.ts
  app/settings/page.tsx
  assets/chevron-right.svg
  assets/circle-help.svg
  assets/heart.svg
  assets/megaphone.svg
  assets/message-alt.svg
  components/Setting/MenuList/index.tsx
  components/Setting/MenuList/style.css.ts
  components/Setting/MyProfile/index.tsx
  components/Setting/MyProfile/style.css.ts
  components/Setting/MypetCarousel/index.tsx
  components/Setting/MypetCarousel/style.css.ts
  components/Setting/MypetCarousel/swiper.css.ts
  styles/global.css.ts
Labels: 🎨 UI

#108 [#102] refactor : 건강수첩 & 에디터 기능 리팩토링
  app/healthlog/edit/page.css.ts
  app/healthlog/edit/page.tsx
  app/healthlog/page.tsx
  app/healthlog/select/page.tsx
  assets/grooming-icon.svg
  assets/log-edit-icon.svg
  components/@common/LogList/LogItem/index.tsx
  components/@common/LogList/LogItem/style.css.ts
  components/@common/LogList/index.tsx
  components/Healthlog/LogDetail/index.tsx
  components/Healthlog/LogDetail/style.css.ts
  components/Healthlog/LogWriteButton/index.tsx
  components/Healthlog/LogWriteButton/style.css.ts
  components/Healthlog/QuickButtons/index.tsx
  components/Healthlog/SubtypeDetail/style.css.ts
  styles/zindex.css.ts
Labels: 🍀 refactor, 🎨 UI

#111 [#107] feat : 이메일 초대 모달
  app/(settingsMenu)/(petmate)/invitation/page.css.ts
  app/(settingsMenu)/(petmate)/invitation/page.tsx
  app/(settingsMenu)/received-invites/page.css.ts
  assets/copy.svg
  assets/letter.png
  components/@common/InvitationForm/InvitationForm.css.ts
  components/@common/Modal/style.css.ts
  components/Setting/Invite/InviteCode/index.tsx
  components/Setting/Invite/InviteCode/mockData.json
  components/Setting/Invite/InviteCode/style.css.ts
  components/Setting/Invite/index.tsx
  components/Setting/Invite/style.css.ts
  constants/inputConstant.ts
Labels: 💫 feat, 🎨 UI

#115 [#113, #105] feat, design : settings 페이지 기능, 디자인 진짜 완성
  app/(settingsMenu)/(petmate)/invitation/page.tsx
  app/settings/page.css.ts
  app/settings/page.tsx
  components/Setting/InviteModal/InviteCode/index.tsx
  components/Setting/InviteModal/InviteCode/mockData.json
  components/Setting/InviteModal/InviteCode/style.css.ts
  components/Setting/InviteModal/index.tsx
  components/Setting/InviteModal/style.css.ts
  components/Setting/MenuList/style.css.ts
  components/Setting/MyPetInfo/index.tsx
  components/Setting/MyPetInfo/style.css.ts
  components/Setting/MypetCarousel/Card/index.tsx
  components/Setting/MypetCarousel/Card/style.css.ts
  components/Setting/MypetCarousel/index.tsx
  components/Setting/MypetCarousel/mockdata.json
  components/Setting/MypetCarousel/style.css.ts
  components/Setting/MypetCarousel/swiper.css.ts
Labels: 💫 feat, 🛠️ fix, 🍀 refactor, 🎨 UI

#119 [#116] feat : 육아일기 건강수첩 공통헤더
  app/diary/detail/[_id]/page.tsx
  app/diary/detail/[_id]/style.css.ts
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  assets/chevron-left.svg
  assets/images/pet-profile-default.svg
  components/@common/BackHeader/index.tsx
  components/@common/BackHeader/style.css.ts
  components/@common/SelectPet/index.tsx
  components/@common/SelectPet/style.css.ts
  components/Diary/DiaryList/style.css.ts
  components/Diary/EmptyDiaryList/style.css.ts
  components/Diary/ImageInput/index.tsx
  components/Diary/ImageInput/style.css.ts
  styles/colors.css.ts
  styles/zindex.css.ts
Labels: 💫 feat, 🍀 refactor

#109 [#104] design 최초 유저 프로필 등록 페이지 스타일링
  app/create/(route)/user-profile/page.css.ts
  app/create/(route)/user-profile/page.tsx
  app/create/pet-group/page.css.ts
  app/create/pet-group/page.tsx
  app/create/user-profile/page.css.ts
  app/create/user-profile/page.tsx
  assets/caution.svg
  assets/confirm.svg
  assets/user-profile-default.svg
  components/@common/ConfirmMessage/ConfirmMessage.css.ts
  components/@common/ConfirmMessage/ConfirmMessage.tsx
  components/@common/InvitationForm/InvitationForm.tsx
  components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.css.ts
  components/Layout/MobileHeaderLogo/MobileHeaderLogo.css.ts
  components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  constants/inputConstant.ts
  styles/global.css.ts
  styles/zindex.css.ts
Labels: 💫 feat, 🎨 UI

#123 [#122] refactor : Root Layout, Template 리팩토링
  app/home/select/page.css.ts
  app/home/select/page.tsx
  app/layout.tsx
  app/no-pet-group/page.css.ts
  app/no-pet-group/page.tsx
  app/template.tsx
  constants/pagesWithHeader.ts
Labels: 🍀 refactor

#118 [#114] refactor : 건강수첩 리팩토링 & 디자인
  app/healthlog/edit/page.css.ts
  app/healthlog/edit/page.tsx
  app/healthlog/page.css.ts
  assets/log-detail-icon.svg
  components/@common/DateInput/index.tsx
  components/@common/DateInput/style.css.ts
  components/@common/LogList/LogItem/index.tsx
  components/@common/LogList/LogItem/style.css.ts
  components/Healthlog/LogDetail/index.tsx
  components/Healthlog/LogDetail/style.css.ts
  components/Healthlog/SearchLocation/style.css.ts
  components/Healthlog/SelectMateDropdown/style.css.ts
  components/Healthlog/SubtypeDetail/index.tsx
  components/Healthlog/SubtypeDetail/style.css.ts
Labels: 🍀 refactor, 🎨 UI

#128 [#126] design : 홈페이지, 펫그룹 참여 모달 스타일링
  app/home/page.tsx
  components/@common/InvitationForm/InvitationForm.css.ts
  components/@common/InvitationForm/InvitationForm.tsx
  components/Home/HomeHealthLogPreview/HomeHealthLogPreview.css.ts
  components/Home/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  components/Home/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/Home/HomePetProfile/HomePetProfile.css.ts
  components/Home/HomePetProfile/HomePetProfile.tsx
  components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  components/Participate/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  components/Participate/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  components/Participate/ReceivedInvitationList/ReceivedInvitationList.tsx
  styles/colors.css.ts
  types/petGroup.ts
  types/receivedInvitation.ts
Labels: 🍀 refactor, 🎨 UI

#134 [#131] refactor : setting 전체적인 리팩토링
  app/(settingsMenu)/(Account)/profile/mockData.json
  app/(settingsMenu)/(Account)/profile/page.tsx
  app/(settingsMenu)/(petmate)/invitation/page.css.ts
  app/(settingsMenu)/(petmate)/member/page.tsx
  app/settings/(accounts)/layout.css.ts
  app/settings/(accounts)/layout.tsx
  app/settings/(accounts)/password/page.css.ts
  app/settings/(accounts)/password/page.tsx
  app/settings/(accounts)/profile/mockData.json
  app/settings/(accounts)/profile/page.css.ts
  app/settings/(accounts)/profile/page.tsx
  app/settings/(petmate)/invitation/mockData.json
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/layout.css.ts
  app/settings/(petmate)/layout.tsx
  app/settings/(petmate)/member/mockData.json
  app/settings/(petmate)/member/page.tsx
  app/settings/(petmate)/petmate.css.ts
  app/settings/ask/page.tsx
  app/settings/faq/page.tsx
  app/settings/notice/page.tsx
  app/settings/page.css.ts
  app/settings/page.tsx
  app/settings/received-invites/mockData.json
  app/settings/received-invites/page.css.ts
  app/settings/received-invites/page.tsx
  assets/camera.svg
  assets/images/letter.png
  assets/images/person-profile-default.svg
  components/@common/ErrorMessage/style.css.ts
  components/@common/Modal/style.css.ts
  components/@common/TitleHeader/style.css.ts
  components/Setting/InviteModal/index.tsx
  components/Setting/InviteModal/style.css.ts
  components/Setting/MenuList/style.css.ts
  components/Setting/MyPetInfo/index.tsx
  components/Setting/MyProfile/index.tsx
  components/Setting/MyProfile/mockData.json
  components/Setting/MyProfile/style.css.ts
  components/Setting/MypetCarousel/index.tsx
  components/Setting/MypetCarousel/mockdata.json
  components/Setting/MypetCarousel/style.css.ts
  constants/pagesWithHeader.ts
  styles/colors.css.ts
Labels: 💫 feat, 🛠️ fix, 🍀 refactor

#129 [#125] design : [새로운 펫 그룹 생성 or 기존 펫그룹 참여 선택] 페이지 (/no-pet-group) 스타일링
  app/no-pet-group/page.css.ts
  app/no-pet-group/page.tsx
  assets/images/mock-up.svg
  components/@common/InvitationForm/InvitationForm.css.ts
Labels: 🎨 UI

#110 [#103] feat : 동물 정보 입력페이지(공용)
  app/(settingsMenu)/(service)/ask/page.tsx
  app/(settingsMenu)/(service)/faq/page.tsx
  app/(settingsMenu)/(service)/notice/page.tsx
  app/page.tsx
  assets/confirm.svg
  assets/user.svg
  components/@common/ErrorMessage/index.tsx
  components/@common/PetRegister/PetDateInput.tsx
  components/@common/PetRegister/component/OptionalCheck/index.tsx
  components/@common/PetRegister/component/OptionalCheck/style.css.ts
  components/@common/PetRegister/index.tsx
  components/@common/PetRegister/style.css.ts
  constants/inputConstant.ts
  public/data/petOptions.ts
Labels: 💫 feat, 🎨 UI, 🥹 incomplete

#121 [#96] refactor, design : 온보딩페이지 코드 리팩토링, UI스타일링 (진행중)
  app/onboarding/onboardingContent/OnboardingData.tsx
  app/onboarding/onboardingContent/OnbordingUI.tsx
  app/onboarding/onboardingContent/style.css.ts
  app/onboarding/page.css.ts
  app/onboarding/page.tsx
  components/Onboarding/index.tsx
  components/Onboarding/styles.css.ts
  public/onboarding/onboarding1.png
  public/onboarding/onboarding2.png
  public/onboarding/onboarding3.png
  public/onboarding/onboarding4.png
  public/onboarding/onboarding5.png
  styles/colors.css.ts
Labels: 🍀 refactor, 🎨 UI, 🥹 incomplete

#136 [#120] feat : 일기 페이지 케밥 구현
  app/_components/DateInput/index.tsx
  app/_components/SelectPet/index.tsx
  app/diary/detail/[_id]/page.tsx
  app/diary/detail/[_id]/style.css.ts
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  public/icons/like.svg
  styles/colors.css.ts
Labels: 💫 feat, 🍀 refactor

#139 [#135] refactor : 전체적인 리팩토링2
  app/_components/Modal/index.tsx
  app/_components/Modal/style.css.ts
  app/settings/(account)/layout.css.ts
  app/settings/(account)/layout.tsx
  app/settings/(account)/password/page.css.ts
  app/settings/(account)/password/page.tsx
  app/settings/(account)/profile/mockData.json
  app/settings/(account)/profile/page.css.ts
  app/settings/(account)/profile/page.tsx
  app/settings/(petmate)/invitation/mockData.json
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/member/mockData.json
  app/settings/(petmate)/member/page.tsx
  app/settings/(service)/ask/page.tsx
  app/settings/(service)/faq/page.tsx
  app/settings/(service)/notice/page.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MyProfile/mockData.json
  app/settings/_components/MypetCarousel/mockdata.json
  app/settings/received-invites/mockData.json
  app/settings/received-invites/page.tsx
Labels: 🛠️ fix, 🍀 refactor

#142 [#141] refactor : 온보딩 리팩토링
  app/(auth)/onboarding/OnboardingData.tsx
  app/(auth)/onboarding/OnbordingUI.tsx
  app/(auth)/onboarding/style.css.ts
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/onboarding/page.tsx
  app/page.css.ts
  app/page.tsx
  app/style.css.ts
  public/images/onboarding/onboarding1.png
  public/images/onboarding/onboarding2.png
  public/images/onboarding/onboarding3.png
  public/images/onboarding/onboarding4.png
  public/images/onboarding/onboarding5.png
  public/images/onboarding1.png
  public/images/onboarding2.png
  public/images/onboarding3.png
  public/images/onboarding4.png
  public/images/onboarding5.png
Labels: 🍀 refactor

#138 [#124] design : Root Layout, /home 페이지 스타일링
  app/_components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.css.ts
  app/_components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.tsx
  app/_components/Layout/MobileHeaderLogo/MobileHeaderLogo.css.ts
  app/_components/Layout/MobileHeaderLogo/MobileHeaderLogo.tsx
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.css.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_constants/pagesWithHeader.ts
  app/_types/petGroup.ts
  app/home/_components/HomePetProfile/HomePetProfile.tsx
  app/home/page.css.ts
  app/home/select/page.tsx
  app/layout.tsx
  public/icons/diary.svg
  public/icons/drop-down-icon-orange.svg
  public/icons/healthlog.svg
  public/icons/home.svg
  public/icons/logo.svg
  public/icons/pet-group-settings.svg
  public/icons/settings.svg
  public/icons/user-profile-default-no-camera.svg
  styles/colors.css.ts
Labels: 🍀 refactor, 🎨 UI

#140 [#130] feat : 토스트 메시지 컴포넌트 구현(토스트 디자인 의견 부탁🙏
  app/_components/Toast/index.tsx
  app/_components/Toast/style.css.ts
  app/layout.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/style.css.ts
  package-lock.json
  package.json
  public/icons/circle-warning.svg
  public/icons/confirm.svg
Labels: 💫 feat

#144 [#143] feat : 모달 스르륵 열리는 효과
  app/_components/ModalContainer/style.css.ts
Labels: 💫 feat

#148 [#146] feat : middleware.ts 설정
  app/(auth)/_components/SignForm/SigninForm.tsx
  app/_api/auth/index.ts
  app/_api/axios.ts
  middleware.ts
Labels: 💫 feat

#150 [#149] refactor : 닉네임 변경 로직 util 함수로 분리
  app/settings/(account)/profile/page.tsx
  app/settings/_utils/checkNickname.ts
  app/settings/_utils/getNicknameState.tsx
Labels: 🍀 refactor

#151 [#145] design : auth 모바일 UI 스타일링
  app/(auth)/_components/AlertModal/index.tsx
  app/(auth)/_components/AlertModal/styles.css.ts
  app/(auth)/_components/SignButton/index.tsx
  app/(auth)/_components/SignButton/style.css.ts
  app/(auth)/_components/SignForm/SignupForm.tsx
  app/(auth)/_components/SignForm/styles.css.ts
  app/(auth)/_components/SignInput/Input.tsx
  app/(auth)/_components/SignInput/styles.css.ts
  app/(auth)/_components/SubmitButton/index.tsx
  app/(auth)/_components/SubmitButton/styles.css.ts
  app/(auth)/login/(route)/email/page.tsx
  app/(auth)/login/(route)/email/style.css.ts
  app/(auth)/login/page.css.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/(route)/email/page.tsx
  app/(auth)/signup/(route)/email/style.css.ts
  app/(auth)/signup/page.css.ts
  app/(auth)/signup/page.tsx
  app/(auth)/style.css.ts
  app/_components/Modal/style.css.ts
  app/_components/SignButton/index.tsx
  app/_components/SignButton/style.css.ts
  public/icons/email-icon.svg
  public/icons/google-icon.svg
  public/icons/google.svg
  public/icons/kakao-icon.svg
  public/images/logo-high-resolution.png
  styles/colors.css.ts
Labels: 🎨 UI

#155 [#130] refactor : 토스트 디자인 변경
  app/_components/Toast/style.css.ts
Labels: 🍀 refactor, 🎨 UI

#158 [#157] 로그아웃 api 연동
  app/_api/auth/index.ts
  app/settings/page.tsx
Labels: 💫 feat

#153 [#137] refactor : 동물 등록 페이지 완룡
  app/_components/PetRegister/PetDateInput.tsx
  app/_components/PetRegister/component/OptionalCheck/index.tsx
  app/_components/PetRegister/component/OptionalCheck/style.css.ts
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/component/PetdateInput/style.css.ts
  app/_components/PetRegister/index.tsx
  app/_components/PetRegister/style.css.ts
  app/_constants/inputConstant.ts
  app/home/pet-register/page.tsx
  app/page.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/pet-register/page.tsx
  hooks/useModal.tsx
  public/data/petOptions.ts
Labels: 🍀 refactor

#156 [#132] refactor : 추가 리팩토링
  .env
  .gitignore
  app/_components/LogList/LogItem/index.tsx
  app/_components/LogList/index.tsx
  app/_components/VanillaCalendar/index.tsx
  app/_components/VanillaCalendar/style.css
  app/healthlog/_components/QuickButtons/index.tsx
  app/healthlog/_components/QuickButtons/style.css.ts
  app/healthlog/_components/SubtypeDetail/index.tsx
  app/healthlog/edit/page.css.ts
  app/healthlog/page.css.ts
Labels: 🍀 refactor

#159 [#154] feat : layout, home api 연동
  app/_api/pets/index.ts
  app/_api/users/index.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_types/petGroup/types.ts
  app/_types/users/types.ts
  app/home/_components/HomePetProfile/HomePetProfile.tsx
  app/layout.tsx
  next.config.js
Labels: 💫 feat

#161 [#160] feat : api 연동
  app/_api/guardians/index.tsx
  app/_api/invitation/index.ts
  app/_api/pets/index.ts
  app/_api/users/index.ts
  app/_types/guardians/types.ts
  app/_types/invitaion/types.ts
  app/_types/pets/types.ts
  app/_types/user/types.ts
  app/settings/(petmate)/member/mockData.json
  app/settings/(petmate)/member/page.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/InviteCode/mockData.json
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MyProfile/mockData.json
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/mockdata.json
  app/settings/received-invites/mockData.json
  app/settings/received-invites/page.tsx
Labels: 💫 feat

#163 [#152] feat : 회원가입 API연동
  app/(auth)/_components/SignForm/SignupForm.tsx
  app/_api/auth/index.ts
  middleware.ts
Labels: 💫 feat

#166 [#164] feat : 일기 api 연동
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryList/index.tsx
  app/diary/edit/page.tsx
Labels: 💫 feat

#171 [#170] feat : api연동 2차...
  app/_api/guardians/index.tsx
  app/_api/invitation/index.ts
  app/_components/InvitationForm/InvitationForm.tsx
  app/_types/invitaion/types.ts
  app/settings/(petmate)/invitation/mockData.json
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/_components/InviteModal/index.tsx
  app/settings/_components/MemberList/index.tsx
Labels: 💫 feat

#174 [#167] feat : 유저 프로필 등록 페이지 api 연동, 리팩토링
  app/_api/users/index.ts
  app/_components/getNicknameHintState/getNicknameHintState.css.ts
  app/_components/getNicknameHintState/getNicknameHintState.tsx
  app/create/user-profile/page.css.ts
  app/create/user-profile/page.tsx
  public/icons/confirm.svg
Labels: 💫 feat, 🍀 refactor

#176 [#175] feat : api연동 3차
  app/_api/guardians/index.tsx
  app/_api/pets/index.ts
  app/_api/users/index.ts
  app/_utils/getPersonImagePath.ts
  app/_utils/getPetImagePath.ts
  app/settings/(account)/profile/mockData.json
  app/settings/(account)/profile/page.tsx
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/(petmate)/petmate.css.ts
  app/settings/_components/InvitationForm/index.tsx
  app/settings/_components/InvitationForm/style.css.ts
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/style.css.ts
  app/settings/_utils/checkNickname.ts
Labels: 💫 feat

#182 [#178] feat : select pet api 연동
  app/_api/diary/index.ts
  app/_api/pets/index.ts
  app/_components/SelectPet/index.tsx
  app/_components/SelectPet/style.css.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryList/index.tsx
  app/diary/page.tsx
  app/diary/select/page.tsx
  middleware.ts
Labels: 💫 feat

#183 [#179] feat : 반려동물 등록 API연결
  app/(auth)/signup/(route)/email/page.tsx
  app/(auth)/signup/page.tsx
  app/_api/pets/index.ts
  app/_components/PetRegister/component/OptionalCheck/style.css.ts
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/component/PetdateInput/style.css.ts
  app/_components/PetRegister/index.tsx
  app/_components/PetRegister/style.css.ts
  app/_constants/inputConstant.ts
  app/_types/petGroup/types.ts
  app/_types/pets/types.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/pet-register/page.tsx
  public/icons/calendarIcon.svg
Labels: 💫 feat

#181 [#180] feat : 건강수첩 나머지 api 연동
  app/_api/log/index.ts
  app/_hooks/usePostLogMutation.tsx
  app/_types/log/types.ts
  app/healthlog/_components/SubtypeDetail/index.tsx
  app/healthlog/create/page.tsx
  app/healthlog/edit/page.tsx
  app/healthlog/page.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  public/data/buttonTypes.ts
Labels: 💫 feat, 🍀 refactor, 🥹 incomplete

#184 [#177] feat : 그룹 참여 모달 api 연동 및 리팩토링
  app/_api/invitation/index.ts
  app/_components/Invitation/InvitationInput.css.ts
  app/_components/Invitation/InvitationInput.tsx
  app/_components/Invitation/InvitationInputError.css.ts
  app/_components/Invitation/InvitationInputError.tsx
  app/_components/Invitation/InvitationSubmitButton.css.ts
  app/_components/Invitation/InvitationSubmitButton.tsx
  app/_types/receivedInvitation.ts
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.css.ts
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.tsx
Labels: 💫 feat, 🍀 refactor, 🎨 UI

#186 [#178] feat : diary api 연동
  app/_api/diary/index.ts
  app/_states/atom.ts
  app/_types/diary/type.ts
  app/diary/_components/Diary/index.tsx
  app/diary/_components/Diary/style.css.ts
  app/diary/_components/DiaryList/index.tsx
  app/diary/_components/ImageInput/index.tsx
  app/diary/detail/[_id]/page.tsx
  app/diary/detail/[_id]/style.css.ts
  app/diary/edit/page.tsx
  app/diary/page.tsx
  app/diary/search/page.tsx
  app/diary/search/style.css.ts
  styles/colors.css.ts
Labels: 💫 feat

#189 [#180] feat : 건강수첩 Edit 페이지 api 연동
  app/_api/log/index.ts
  app/_components/LogList/LogItem/index.tsx
  app/_components/LogList/index.tsx
  app/_hooks/usePostLogMutation.tsx
  app/_types/log/types.ts
  app/healthlog/_components/LogDetail/index.tsx
  app/healthlog/_components/QuickButtons/index.tsx
  app/healthlog/_components/SelectMateDropdown/index.tsx
  app/healthlog/create/page.tsx
  app/healthlog/edit/[id]/page.css.ts
  app/healthlog/edit/[id]/page.tsx
  app/healthlog/page.tsx
  app/healthlog/select/page.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  middleware.ts
  tsconfig.json
Labels: 💫 feat, 🤯 help, 🍀 refactor

#190 [feat] 프로필, 비밀번호 변경 api연동, 기능 리팩토링
  app/_api/invitation/index.ts
  app/_api/users/index.ts
  app/_components/TitleHeader/index.tsx
  app/_types/invitaion/types.ts
  app/settings/(account)/layout.tsx
  app/settings/(account)/password/page.tsx
  app/settings/(account)/profile/page.css.ts
  app/settings/(account)/profile/page.tsx
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/layout.tsx
  app/settings/_components/EmptyMyInvitation/index.tsx
  app/settings/_components/EmptyMyInvitation/style.css.ts
  app/settings/_components/EmptyRecivedInvitation/index.tsx
  app/settings/_components/EmptyRecivedInvitation/style.css.ts
  app/settings/_components/InviteModal/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_utils/checkNickname.ts
  app/settings/_utils/getNicknameState.tsx
  app/settings/page.tsx
  app/settings/received-invites/page.css.ts
  app/settings/received-invites/page.tsx
  public/icons/confirm.svg
  public/icons/letter-gray.svg
Labels: 💫 feat, 🛠️ fix, 🍀 refactor, 🎨 UI

#191 [#185] refactor : 첫 이용 플로우 리팩토링
  app/(first-time-use)/create-user-profile/page.css.ts
  app/(first-time-use)/create-user-profile/page.tsx
  app/(first-time-use)/home-select/page.css.ts
  app/(first-time-use)/home-select/page.tsx
  app/(first-time-use)/no-pet-group/page.css.ts
  app/(first-time-use)/no-pet-group/page.tsx
  app/(first-time-use)/pet-register/page.tsx
  app/_api/users/index.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_constants/pagesWithHeader.ts
  app/create/pet-group/page.css.ts
  app/create/pet-group/page.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.tsx
  app/home/page.tsx
  app/home/select/page.tsx
Labels: 🐛 bug, 🍀 refactor

#194 [#193] feat : settings 페이지 서버렌더링
  app/_api/auth/index.ts
  app/_api/guardians/index.tsx
  app/_api/pets/index.ts
  app/_components/Toast/index.tsx
  app/_components/Toast/style.css.ts
  app/settings/(account)/profile/page.css.ts
  app/settings/(account)/profile/page.tsx
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/_components/Invitation/index.tsx
  app/settings/_components/InvitationForm/index.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/Logout/index.tsx
  app/settings/_components/Member/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/Profile/index.tsx
  app/settings/_components/ReceivedInvites/index.tsx
  app/settings/_components/ReceivedInvites/style.css.ts
  app/settings/page.css.ts
  app/settings/page.tsx
  app/settings/received-invites/page.tsx
Labels: 💫 feat, ❓ question

#196 [#180] feat : 건강수첩 에디트 페이지 api 연동
  app/_components/BackHeader/style.css.ts
  app/_components/LogList/index.tsx
  app/_constants/pagesWithHeader.ts
  app/healthlog/_components/CreateForm/index.tsx
  app/healthlog/_components/CreateForm/style.css.ts
  app/healthlog/_components/EditForm/index.tsx
  app/healthlog/_components/EditForm/style.css.ts
  app/healthlog/_components/EmptyHealthLog/style.css.ts
  app/healthlog/_components/HealthlogContent/index.tsx
  app/healthlog/_components/HealthlogContent/style.css.ts
  app/healthlog/_components/QuickButtons/index.tsx
  app/healthlog/_components/SearchLocation/index.tsx
  app/healthlog/_components/SelectMateDropdown/index.tsx
  app/healthlog/_components/SubtypeDetail/index.tsx
  app/healthlog/create/page.tsx
  app/healthlog/edit/[id]/page.tsx
  app/healthlog/page.css.ts
  app/healthlog/page.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  package-lock.json
  package.json
Labels: 💫 feat

#201 [refactor] 전체적인 fix, refactor
  app/_api/guardians/index.tsx
  app/_api/pets/index.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_constants/pagesWithHeader.ts
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/(petmate)/petmate.css.ts
  app/settings/_components/Invitation/index.tsx
  app/settings/_components/InvitationForm/index.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/index.tsx
  app/settings/_components/Member/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyProfile/style.css.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/Profile/index.tsx
Labels: 💫 feat, 🛠️ fix, 🍀 refactor, 🎨 UI

#206 [#197] feat : 무한스크롤 & 비디오 input
  app/_api/diary/index.ts
  app/_components/SelectPet/index.tsx
  app/_hooks/useInfiniteScroll.tsx
  app/_types/diary/type.ts
  app/diary/_components/CreateForm/index.tsx
  app/diary/_components/Diary/index.tsx
  app/diary/_components/Diary/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryDetail/style.css.ts
  app/diary/_components/DiaryDetail/swiper.css.ts
  app/diary/_components/DiaryList/index.tsx
  app/diary/_components/EditForm/index.tsx
  app/diary/_components/ImageInput/index.tsx
  app/diary/_components/VideoInput/index.tsx
  app/diary/constant.ts
  app/diary/detail/[id]/page.tsx
  app/diary/page.tsx
  app/diary/search/page.tsx
Labels: 💫 feat, 🍀 refactor

#210 [#209] fix : 프로필 변경 api와 기능 리팩토링, 카드 ui 스켈레톤
  app/_api/invitation/index.ts
  app/_api/users/index.ts
  app/_components/Toast/index.tsx
  app/settings/_components/EmptyMyInvitation/index.tsx
  app/settings/_components/Logout/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/Profile/index.tsx
  app/settings/_components/Skeleton/index.tsx
  app/settings/_components/Skeleton/style.css.ts
  app/settings/page.tsx
Labels: 🛠️ fix, 🍀 refactor

#212 [#211] feat : 로딩스피너
  app/_states/atom.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/Form/CreateForm/index.tsx
  app/diary/_components/Form/CreateForm/style.css.ts
  app/diary/_components/Form/EditForm/index.tsx
  app/diary/_components/Input/DateInput/index.tsx
  app/diary/_components/Input/DateInput/style.css.ts
  app/diary/_components/Input/FormInput/index.tsx
  app/diary/_components/Input/ImageInput/index.tsx
  app/diary/_components/Input/ImageInput/style.css.ts
  app/diary/_components/Input/VideoInput/index.tsx
  app/diary/_components/Input/VideoInput/style.css.ts
  app/diary/_components/Loading/index.tsx
  app/diary/_components/Loading/style.css.ts
  app/diary/constant.ts
  app/diary/create/page.tsx
  app/diary/edit/[id]/page.tsx
  app/diary/search/page.tsx
  app/diary/search/style.css.ts
  package-lock.json
  package.json
  public/animation/loading-spinner-lg.json
  public/animation/loading-spinner-sm.json
  styles/zindex.css.ts
Labels: 💫 feat, 🛠️ fix

#214 [#213] feat : 404 페이지 구현
  app/404/_components/LostPet/index.tsx
  app/404/_components/LostPet/style.css.ts
  app/404/page.css.ts
  app/404/page.tsx
  app/_api/lostpet/index.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_components/LogList/LogItem/index.tsx
  app/_components/LogList/LogItem/style.css.ts
  app/_components/LogList/index.tsx
  app/_components/VanillaCalendar/style.css
  app/_hooks/usePostLogMutation.tsx
  app/healthlog/_components/CreateForm/index.tsx
  app/healthlog/_components/EditForm/index.tsx
  app/healthlog/_components/QuickButtons/index.tsx
  app/healthlog/_components/SubtypeDetail/index.tsx
  next.config.js
  public/images/illustration-404.png
  public/images/illustration-bg-404.png
Labels: 💫 feat, 🍀 refactor

#216 [#208] refactor : next/font로 로컬 폰트 적용 및 최적화
  app/layout.tsx
  fonts/PretendardVariable.woff2
  fonts/layout.tsx
  styles/global.css.ts
Labels: 💫 feat

#217 [#213] refactor : 세부 리팩토링
  app/_api/pets/index.ts
  app/not-found/_components/LostPet/index.tsx
  app/not-found/_components/LostPet/style.css.ts
  app/not-found/page.css.ts
  app/not-found/page.tsx
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/pet-info/[id]/page.tsx
Labels: 🍀 refactor

#218 [#215] refactor : mobile header, pc header
  app/_components/Layout/MainWrapper/MainWrapper.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_components/Layout/PcHeader/PcHeader.tsx
  app/_components/Layout/PcHeaderNav/PcHeaderNav.css.ts
  app/_components/Layout/PcHeaderNav/PcHeaderNav.tsx
  app/home/page.tsx
  app/template.tsx
  package-lock.json
  package.json
Labels: 🍀 refactor

#220 [feat] 프로필 변경, 비밀번호 페이지 변경, 로그아웃 로딩 중
  app/_api/guardians/index.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/settings/(account)/password/page.css.ts
  app/settings/(account)/profile/page.css.ts
  app/settings/_components/Logout/index.tsx
  app/settings/_components/Member/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/swiper.css.ts
  app/settings/_components/Profile/index.tsx
  app/settings/_components/ReceivedInvites/index.tsx
  app/settings/page.css.ts
  app/settings/page.tsx
Labels: 🛠️ fix, 🍀 refactor

#221 [#215] refactor : mobile header, pc header
  app/_components/Layout/MainWrapperPcOnly/MainWrapperPcOnly.css.ts
  app/_components/Layout/MainWrapperPcOnly/MainWrapperPcOnly.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/_components/Layout/PcHeaderNav/PcHeaderNav.css.ts
  app/_components/Layout/PcHeaderNav/PcHeaderNav.tsx
  app/_constants/pagesWithHeader.ts
  app/template.tsx
Labels: 🐛 bug, 🍀 refactor

#224 [#223] feat, design: 이미지모달 공용 컴포넌트 만들기
  app/(auth)/login/page.tsx
  app/_api/auth/index.ts
  app/_components/Modal/ImageModal/index.tsx
  app/_components/Modal/ImageModal/style.css.ts
  public/images/modal/RegisterImage.png
  public/images/modal/SignupImage.png
  public/images/modal/editImage.png
  public/images/modal/warningImage.png
  tsconfig.json
Labels: 💫 feat

#227 [refactor] settings 마지막 기능 리팩토링
  app/_components/Loading/index.tsx
  app/_components/Loading/style.css.ts
  app/diary/_components/Form/CreateForm/index.tsx
  app/diary/_components/Form/EditForm/index.tsx
  app/settings/(petmate)/invitation/page.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/Logout/index.tsx
  app/settings/_components/Member/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/Profile/index.tsx
  package-lock.json
  package.json
Labels: 🍀 refactor

#228 [#222] feat : 최초 이용 플로우 추가 기능, 태블릿 반응형
  app/(first-time-use)/create-user-profile/page.css.ts
  app/(first-time-use)/create-user-profile/page.tsx
  app/(first-time-use)/no-pet-group/page.css.ts
  app/_components/Invitation/InvitationInput.css.ts
  app/_components/Invitation/InvitationSubmitButton.css.ts
  app/_components/getNicknameHintState/getNicknameHintState.css.ts
  app/home/_components/HomePetProfile/HomePetProfile.css.ts
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.css.ts
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.tsx
  app/home/page.css.ts
Labels: 💫 feat, 🎨 UI

#230 [#229] feat : 태블릿 반응형
  app/_components/Modal/index.tsx
  app/_components/Modal/style.css.ts
  app/settings/(petmate)/petmate.css.ts
  app/settings/_components/EmptyMyInvitation/style.css.ts
  app/settings/_components/EmptyRecivedInvitation/index.tsx
  app/settings/_components/EmptyRecivedInvitation/style.css.ts
  app/settings/_components/InvitationForm/style.css.ts
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/InviteCode/style.css.ts
  app/settings/_components/InviteModal/index.tsx
  app/settings/_components/InviteModal/style.css.ts
  app/settings/_components/Logout/index.tsx
  app/settings/_components/Logout/style.css.ts
  app/settings/_components/MenuList/index.tsx
  app/settings/_components/MenuList/style.css.ts
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyPetInfo/style.css.ts
  app/settings/_components/MyProfile/style.css.ts
  app/settings/_components/MypetCarousel/style.css.ts
  app/settings/_components/MypetCarousel/swiper.css.ts
  app/settings/_components/ReceivedInvites/style.css.ts
  app/settings/page.css.ts
  app/settings/page.tsx
Labels: 🎨 UI

#232 [#231] ui : 건강수첩 태블릿 반응형
  app/_components/LogList/LogItem/style.css.ts
  app/_components/LogList/index.tsx
  app/_components/LogList/style.css.ts
  app/_components/VanillaCalendar/style.css
  app/healthlog/_components/EmptyHealthLog/style.css.ts
  app/healthlog/_components/HealthlogContent/style.css.ts
  app/healthlog/_components/QuickButtons/style.css.ts
  app/healthlog/page.css.ts
Labels: 🎨 UI

#233 [#225] 소희님 PR에 이전브랜치 유효한 코드 병합하기 1
  app/_components/PetRegister/component/OptionalCheck/index.tsx
  app/_components/PetRegister/component/OptionalCheck/style.css.ts
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/component/RadioInput/GenderRadio.tsx
  app/_components/PetRegister/component/RadioInput/NeuteringRadio.tsx
  app/_components/PetRegister/component/RadioInput/style.css.ts
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
  app/settings/pet-register/page.tsx
  public/icons/check/grey-check-icon.svg
  public/icons/check/orange-check-icon.svg
Labels: 💫 feat, 🍀 refactor, 🎨 UI

#235 [#234] fix : 최초 이용 페이지들, 홈 페이지 QA 에러 디버깅
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.css.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  app/home/_components/HomePetProfile/HomePetProfile.tsx
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.tsx
  app/home/page.tsx
Labels: 🐛 bug

#236 [#231] ui : 건강수첩 나머지 태블릿 반응형, 리팩토링
  app/_components/LostPet/index.tsx
  app/_components/LostPet/style.css.ts
  app/_components/LostPetSkeleton/index.tsx
  app/_components/LostPetSkeleton/style.css.ts
  app/healthlog/_components/CreateForm/index.tsx
  app/healthlog/_components/CreateForm/style.css.ts
  app/healthlog/_components/EditForm/index.tsx
  app/healthlog/_components/EditForm/style.css.ts
  app/healthlog/_components/SubtypeDetail/style.css.ts
  app/home/page.css.ts
  app/not-found.style.css.ts
  app/not-found.tsx
Labels: 🍀 refactor, 🎨 UI

#238 [#237] fix : qa 버그 잡기
  app/_api/auth/index.ts
  app/_components/TitleHeader/style.css.ts
  app/settings/(account)/password/page.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/_components/Member/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/swiper.css.ts
  app/settings/_components/Skeleton/style.css.ts
Labels: 🛠️ fix

#239 [#225] feat : 소희님 PR에 이전브랜치 유효한 작업 병합, 반려동물 수정폼에서 수정, 삭제 기능
  app/_api/guardians/index.tsx
  app/_api/pets/index.ts
  app/_components/Modal/ImageModal/index.tsx
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/component/RadioInput/style.css.ts
  app/_types/petGroup/types.ts
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
Labels: 💫 feat

#241 [#240] feat : refresh-token 기능
  app/_api/auth/index.ts
  app/_api/axios.ts
  package-lock.json
  package.json
Labels: 💫 feat

#245 [#244] fix : 두번째 QA 버그 잡기
  app/_components/Modal/style.css.ts
  app/diary/_components/Diary/style.css.ts
  app/settings/(account)/profile/page.css.ts
  app/settings/(petmate)/petmate.css.ts
  app/settings/_components/EmptyMyInvitation/style.css.ts
  app/settings/_components/EmptyRecivedInvitation/style.css.ts
  app/settings/_components/Invitation/index.tsx
  app/settings/_components/InvitationForm/index.tsx
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/InviteModal/InviteCode/style.css.ts
  app/settings/_components/InviteModal/style.css.ts
  app/settings/_components/Member/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MyPetInfo/style.css.ts
  app/settings/_components/MyProfile/style.css.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/style.css
  app/settings/_components/MypetCarousel/styles.css.ts
  app/settings/_components/MypetCarousel/swiper.css.ts
  app/settings/_components/Profile/index.tsx
  app/template.tsx
Labels: 🛠️ fix

#247 [#234] fix : 프로필 이미지 비율 수정
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.css.ts
Labels: 🎨 UI

#248 [#204] feat : SEO (라이트하우스 seo 100점 만들기 +a)
  app/_constants/index.ts
  app/_constants/metadata.ts
  app/home/page.tsx
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
Labels: 💫 feat

#251 [#250] refacotr : 반려동물 폼 리팩토링
  app/_components/PetRegister/index.tsx
  app/_components/PetRegister/style.css.ts
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
  app/settings/pet-register/page.tsx
Labels: 🍀 refactor, 🎨 UI

#256 [fix] 3번째 QA 버그잡기, 로딩 스피너 구현
  app/_api/guardians/index.tsx
  app/_api/pets/index.ts
  app/_components/Modal/style.css.ts
  app/_components/Spinner/index.tsx
  app/_components/Spinner/style.css.ts
  app/settings/(account)/loading.tsx
  app/settings/(petmate)/invitation/page.tsx
  app/settings/(petmate)/loading.tsx
  app/settings/(petmate)/member/page.tsx
  app/settings/(petmate)/petmate.css.ts
  app/settings/_components/EmptyRecivedInvitation/index.tsx
  app/settings/_components/ListItem/index.tsx
  app/settings/_components/ListItem/style.css.ts
  app/settings/_components/Member/index.tsx
  app/settings/_components/MemberList/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/style.css
  app/settings/_components/MypetCarousel/swiper.css
  app/settings/_components/Profile/index.tsx
  app/settings/_components/ReceivedInvites/index.tsx
  app/settings/page.tsx
  app/settings/received-invites/layout.tsx
  app/settings/received-invites/loading.tsx
  app/settings/received-invites/page.tsx
  public/animation/Spinner-1s-54px.svg
Labels: 🛠️ fix, 🍀 refactor

#258 [#257] fix : 마지막 리팩토링 & 버그 픽스
  app/_api/lostpet/index.ts
  app/_components/LostPet/index.tsx
  app/_components/LostPetSkeleton/style.css.ts
Labels: 🛠️ fix

#260 [#259] feat : 소셜로그인 연동
  app/(auth)/_components/AuthContext.tsx
  app/(auth)/_components/RedirectToHome/index.tsx
  app/(auth)/_components/SignButton/GoogleButton.tsx
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/(auth)/_components/SignButton/index.tsx
  app/(auth)/_components/SignButton/style.css.ts
  app/(auth)/login/page.tsx
  app/(auth)/loginflow/page.tsx
  app/_api/auth/index.ts
  app/_api/pets/index.ts
  app/_api/users/index.ts
  app/_components/PetRegister/index.tsx
  app/_components/PetRegister/style.css.ts
  app/_states/atom.ts
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
  app/style.css.ts
  lib/auth.ts
  package-lock.json
  package.json
Labels: 💫 feat, 🛠️ fix

#262 [#254] UI : PC 반응형 1차 버전 구현
  app/_components/Layout/MainWrapper/MainWrapper.css.ts
  app/_components/Layout/MainWrapper/MainWrapper.tsx
  app/_components/Layout/MainWrapperPcOnly/MainWrapperPcOnly.css.ts
  app/_components/Layout/MainWrapperPcOnly/MainWrapperPcOnly.tsx
  app/_components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.css.ts
  app/_components/Layout/MobileHeaderLogo/MobileHeaderLogo.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/template.tsx
  public/images/pc-bg.jpg
Labels: 🎨 UI

#264 [#261 #242] : style : diary 태블릿 반응형 & 리팩토링
  app/_api/diary/index.ts
  app/_components/Loading/style.css.ts
  app/diary/_components/Diary/index.tsx
  app/diary/_components/Diary/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryDetail/style.css.ts
  app/diary/_components/DiaryDetail/swiper.css
  app/diary/_components/DiaryList/index.tsx
  app/diary/_components/Form/CreateForm/index.tsx
  app/diary/_components/Form/EditForm/index.tsx
  app/diary/_components/Input/ImageInput/style.css.ts
  app/diary/_components/Input/VideoInput/index.tsx
  app/diary/create/page.tsx
  app/diary/detail/[id]/page.tsx
  app/diary/edit/[id]/page.tsx
  app/diary/page.tsx
  app/diary/search/page.tsx
  app/diary/search/style.css.ts
  app/diary/style.css.ts
Labels: 🍀 refactor, 🎨 UI

#265 [#257] refactor : 건강수첩 리팩토링 파이널
  app/healthlog/_components/CreateForm/index.tsx
  app/healthlog/_components/EditForm/index.tsx
  app/not-found.style.css.ts
Labels: 🍀 refactor

#267 [#266] feat : setting 페이지 로딩 스켈레톤 적용
  app/_api/invitation/index.ts
  app/settings/(petmate)/member/page.tsx
  app/settings/_components/Invitation/index.tsx
  app/settings/_components/ListItem/Skeleton/index.tsx
  app/settings/_components/ListItem/Skeleton/style.css.ts
  app/settings/_components/Member/index.tsx
  app/settings/_components/MyProfile/Skeleton/index.tsx
  app/settings/_components/MyProfile/Skeleton/style.css.ts
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/MyProfile/style.css.ts
  app/settings/_components/MypetCarousel/Skeleton/index.tsx
  app/settings/_components/MypetCarousel/Skeleton/style.css.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/page.css.ts
  app/settings/page.tsx
  public/icons/chevron-right.svg
  public/icons/circle-help.svg
  public/icons/heart.svg
  public/icons/megaphone.svg
  public/icons/message-alt.svg
Labels: 💫 feat

#268 [#253] refactor : 최초 이용 페이지들, 홈 페이지 고도화
  app/_components/Layout/MobileHeaderLogo/MobileHeaderLogo.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.css.ts
  app/_components/Layout/PcHeaderNav/PcHeaderNav.tsx
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.css.ts
  app/home/_components/HomeHealthLogPreview/HomeHealthLogPreview.tsx
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.css.ts
  app/home/_components/ReceivedInvitationList/ReceivedInvitationList.tsx
  styles/global.css.ts
Labels: 🍀 refactor

#273 [#270] fix : QA피드백 반영2 (혜윤)
  app/(auth)/_components/SignButton/GoogleButton.tsx
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/_api/pets/index.ts
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/index.tsx
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/pet-info/[id]/page.tsx
Labels: 🛠️ fix

#275 refactor : 검색 페이지, pet select 페이지
  app/_components/SelectPet/index.tsx
  app/_components/SelectPet/style.css.ts
  app/diary/loading.tsx
  app/diary/search/page.tsx
  app/diary/search/style.css.ts
  public/images/no-search-result.png
Labels: 🍀 refactor

#276 [#253] refactor : 홈 관련 QA 반영
  app/home/layout.tsx
  app/home/page.tsx
  app/settings/_components/Logout/index.tsx
Labels: 🍀 refactor

#277 refactor : 로그아웃 시 invites 캐시 삭제
  app/settings/_components/Logout/index.tsx
Labels: 🍀 refactor
