Repository ppp-team/my-pet-log, pull requests merged in 2024-04, with the labels that each got.

#314 [#313] feat : settings 페이지의 구독 관련 API 연동
  app/_api/subscription/index.ts
  app/_types/subscriptions/types.ts
  app/settings/(pet-subscriber)/blocked-user/loading.tsx
  app/settings/(pet-subscriber)/blocked-user/page.tsx
  app/settings/(pet-subscriber)/layout.tsx
  app/settings/(pet-subscriber)/subscriber/loading.tsx
  app/settings/(pet-subscriber)/subscriber/page.tsx
  app/settings/_components/Blocked-User-List/index.tsx
  app/settings/_components/Blocked-User-List/style.css.ts
  app/settings/_components/EmptyBlockedUser/index.tsx
  app/settings/_components/EmptyBlockedUser/style.css.ts
  app/settings/_components/EmptySubscriber/index.tsx
  app/settings/_components/EmptySubscriber/style.css.ts
  app/settings/_components/Pet-Subscriber-List/index.tsx
  app/settings/_components/Pet-Subscriber-List/style.css.ts
  app/settings/subscriptions/loading.tsx
  app/settings/subscriptions/page.tsx
  public/icons/empty-blocked-user-icon.svg
Labels: 💫 feat

#315 [#298] feat : 댓글창 애니메이션 구현
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/_components/CommentModalContainer/index.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
Labels: 💫 feat

#316 [#302] feat : 대댓글 post api 로직 구현 및 오류 수정
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
Labels: 💫 feat, 🛠️ fix

#317 [#307] feat : 알림센터 목록 api 연동
  app/_api/notifications/index.ts
  app/_types/notifications/types.ts
  app/notification/_components/Notification/Notification.css.ts
  app/notification/_components/Notification/Notification.tsx
  app/notification/_components/NotificationArea/NotificationArea.tsx
  app/notification/page.tsx
Labels: 💫 feat, 🎨 UI

#320 fix : build error
  app/notification/_components/NotificationArea/NotificationArea.tsx
  app/notification/page.tsx
Labels: 🛠️ fix

#319 [#318] feat : 일기 공개 비공개, refactor : 일기 수정 api
  app/_states/atom.ts
  app/_types/diary/type.ts
  app/diary/_components/Diary/index.tsx
  app/diary/_components/Form/CreateForm/index.tsx
  app/diary/_components/Form/EditForm/index.tsx
  app/diary/_components/Input/ImageInput/index.tsx
  app/diary/_components/Input/PublicPrivateToggle/index.tsx
  app/diary/_components/Input/PublicPrivateToggle/style.css.ts
  app/diary/_components/Input/VideoInput/index.tsx
  public/icons/lock.svg
Labels: 💫 feat, 🍀 refactor

#321 [#302] feat : 답글(대댓글) 수정, 좋아요, 삭제 즉시 반영 & @닉네임 태그 적용
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
Labels: 💫 feat

#323 [#298] feat : 피드 api 연동
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/(diary)/constant.ts
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/friend-pet/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryList/index.tsx
  app/diary/_components/Feed/index.tsx
  app/diary/_components/Feed/style.css.ts
  app/diary/_components/Feed/swiper.css
  app/diary/_components/FeedList/index.tsx
  app/diary/detail/[id]/page.tsx
  app/diary/search/page.tsx
Labels: 💫 feat

#324 [#307] feat : 알림센터 전체 삭제, 전체 읽음 처리 api 연동
  app/_api/notifications/index.ts
  app/notification/_components/HasNotification/HasNotification.css.ts
  app/notification/_components/HasNotification/HasNotification.tsx
  app/notification/_components/NoNotification/NoNotification.css.ts
  app/notification/_components/Notification/Notification.tsx
  app/notification/_components/NotificationArea/NotificationArea.tsx
  app/notification/page.tsx
Labels: 💫 feat, 🎨 UI

#325 fix: 경로 오류 수정 + 대댓글 api 엔드포인트 수정 반영
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/(diary)/my-pet/page.tsx
  app/diary/_components/DiaryDetail/Comment/index.tsx
Labels: 🐛 bug

#326 [#298] feat : 피드 무한스크롤
  app/diary/_components/Feed/index.tsx
  app/diary/_components/FeedList/index.tsx
Labels: 💫 feat

#327 [#298] feat : 피드 좋아요 구현
  app/diary/_components/Feed/index.tsx
  public/icons/heart-icon.svg
  styles/colors.css.ts
Labels: 💫 feat

#330 [#328] refactor : 대댓글 리팩토링
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/Comment/style.css.ts
  app/diary/_components/DiaryDetail/ReComment/index.tsx
Labels: 🍀 refactor

#333 [#328] fix : petId prop 오류 해결
  app/diary/_components/DiaryDetail/Comment/index.tsx
Labels: 🛠️ fix

#334 [#322] Refactor : subscriptions 관련 UI 및 기능 수정
  app/settings/_components/EmptyBlockedUser/index.tsx
  app/settings/_components/ListItem/Skeleton/index.tsx
  app/settings/_components/ListItem/Skeleton/style.css.ts
  app/settings/_components/Pet-Subscriber-List/index.tsx
Labels: 🍀 refactor

#335 [#298] feat : 댓글 무한스크롤 구현
  app/diary/_components/CommentModalContainer/index.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
  app/diary/_components/Feed/NoMedia/index.tsx
  app/diary/_components/Feed/index.tsx
  app/diary/_components/Feed/style.css.ts
  styles/zindex.css.ts
Labels: 💫 feat

#336 [#298] feat : 댓글 최상위로 스크롤 다 되면 그때 모달이 닫히도록 수정
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/CommentModalContainer/index.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
Labels: 💫 feat

#337 [#298] feat : 좋아요 목록 리스트
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/Feed/LikeList/index.tsx
  app/diary/_components/Feed/LikeList/style.css.ts
  app/diary/_components/Feed/index.tsx
  styles/colors.css.ts
  styles/zindex.css.ts
Labels: 💫 feat

#340 [#298] fix : 피드 빌드 에러
  app/diary/(diary)/friend-pet/page.tsx
Labels: 🛠️ fix

#343 Fix : 소셜로그인 에러
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/_components/PetRegister/index.tsx
  lib/auth.ts
Labels: 🐛 bug

#341 💪 피드 파이널 스퍼트
  app/_api/diary/index.ts
  app/_states/atom.ts
  app/_types/diary/type.ts
  app/diary/(diary)/friend-pet/loading.tsx
  app/diary/(diary)/friend-pet/style.css.ts
  app/diary/_components/CommentModalContainer/Comment/index.tsx
  app/diary/_components/CommentModalContainer/Comment/style.css.ts
  app/diary/_components/CommentModalContainer/EmptyComment/index.tsx
  app/diary/_components/CommentModalContainer/EmptyComment/style.css.ts
  app/diary/_components/CommentModalContainer/index.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
  app/diary/_components/Feed/LikeList/index.tsx
  app/diary/_components/Feed/LikeList/style.css.ts
  app/diary/_components/Feed/NoMedia/index.tsx
  app/diary/_components/Feed/NoMedia/style.css.ts
  app/diary/_components/Feed/index.tsx
  app/diary/_components/Feed/style.css.ts
  app/diary/_components/FeedList/index.tsx
  styles/colors.css.ts
  styles/zindex.css.ts
Labels: 🛠️ fix

#342 [#328] fix : 대댓글 마지막 마무리
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryDetail/style.css.ts
Labels: 🛠️ fix

#344 Fix: 반려동물 등록폼 코드 롤백
  app/_components/PetRegister/index.tsx
Labels: 🛠️ fix

#346 [#345] feat : 알림센터 인피니트 스크롤, 태블릿 반응형 UI
  app/_api/notifications/index.ts
  app/notification/_components/HasNotification/HasNotification.css.ts
  app/notification/_components/HasNotification/HasNotification.tsx
  app/notification/_components/Notification/Notification.tsx
  app/notification/_components/NotificationArea/NotificationArea.tsx
  app/notification/_constants/constants.ts
  app/notification/page.tsx
Labels: 💫 feat, 🎨 UI

#348 Fix: 구글 소셜로그인 에러
  app/(auth)/_components/SignButton/GoogleButton.tsx
Labels: 🛠️ fix

#347 QA FIX
  app/_api/diary/index.ts
  app/diary/_components/CommentModalContainer/Comment/index.tsx
  app/diary/_components/CommentModalContainer/Comment/style.css.ts
  app/diary/_components/Feed/LikeList/index.tsx
  app/diary/_components/Feed/LikeList/style.css.ts
Labels: 🛠️ fix

#350 [#349] QA fix : 일기 검색 api 재연동 & 펫 이름 10자 초과 중복검사x
  app/_api/diary/index.ts
  app/_components/PetRegister/index.tsx
  app/diary/search/page.tsx
  app/settings/_components/EditPetRegisterForm/index.tsx
Labels: 🛠️ fix

#352 [#351] Refactor : 경로에 알맞게 카드캐러셀 연필모양 보이게 하기
  app/settings/_components/InviteModal/InviteCode/index.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MypetCarousel/index.tsx
Labels: 🍀 refactor

#353 [#298] fix : 펫 구독 시 동일한 펫 구독
  app/_states/atom.ts
  app/diary/_components/CommentModalContainer/Comment/index.tsx
  app/diary/_components/Feed/index.tsx
  app/diary/_components/Feed/style.css.ts
  app/settings/_components/SubscriptionList/index.tsx
Labels: 🛠️ fix

#355 [#328] refactor : QA 수정사항 반영 리팩토링
  app/_components/VanillaCalendar/index.tsx
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
  app/diary/_components/DiaryDetail/index.tsx
  app/healthlog/_components/SelectMateDropdown/style.css.ts
Labels: 🍀 refactor
