Repository ppp-team/my-pet-log, pull requests merged in 2024-01, with the labels that each got.

#6 [#5] chore : global css파일 생성
  app/layout.tsx
  styles/global.css.ts
Labels: 🧹 chore

#11 [#10] feat : 관리 페이지 레이아웃, 카드 캐러셸 구현
  app/globals.css
  app/settings/_components/MyProfile/index.tsx
  app/settings/_components/Mypet/index.tsx
  app/settings/page.css.ts
  app/settings/page.tsx
  components/Logout/index.tsx
  components/MyProfile/index.tsx
  components/MyProfile/style.css.ts
  components/MypetCarousel/Card/index.tsx
  components/MypetCarousel/Card/style.css.ts
  components/MypetCarousel/index.tsx
  components/MypetCarousel/mockdata.json
  components/MypetCarousel/style.css.ts
Labels: 💫 feat

#12 [#9] feat: 홈페이지 메인 화면 생성
  app/home/page.css.ts
  app/home/page.tsx
  components/HomeHealthLogPreview/HomeHealthLogTaskItem.tsx
  components/HomeHealthLogPreview/HomeHealthLogTaskList.tsx
  components/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/HomePetProfile/HomePetProfile.tsx
Labels: 💫 feat

#8 [#3] feat : 온보딩, 로그인, 회원가입 페이지 레이아웃 제작
  app/login/(route)/email/page.tsx
  app/login/page.tsx
  app/onboarding/page.tsx
  app/signup/(route)/email/page.tsx
  app/signup/page.tsx
  components/Pagination/index.tsx
  components/Pagination/styles.css.ts
  components/commons/buttons/SignButton.tsx
  components/commons/buttons/style.css.ts
  constatnts/inputConstant.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: 💫 feat

#19 [#16] feat : 최초 이용 관련 페이지 일괄 생성
  app/(participateModal)/@modal/(.)participate/page.tsx
  app/(participateModal)/@modal/default.tsx
  app/(participateModal)/layout.tsx
  app/(participateModal)/participate/page.tsx
  app/(participateModal)/select/page.css.ts
  app/(participateModal)/select/page.tsx
  app/create/(route)/petgroup/page.css.ts
  app/create/(route)/petgroup/page.tsx
  app/create/(route)/userprofile/page.css.ts
  app/create/(route)/userprofile/page.tsx
  components/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/ParticipatePetGroupModal/PariticipatePetCroupModal.css.ts
  components/ParticipatePetGroupModal/PariticipatePetCroupModal.tsx
Labels: 💫 feat

#20 [#13] feat : diary page 레이아웃
  app/diary/card/[cardid]/page.tsx
  app/diary/card/[cardid]/style.css.ts
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  app/diary/page.tsx
  app/page.tsx
  assets/PlusIcon.tsx
  assets/edit.svg
  components/@common/SelectPet/index.tsx
  components/@common/SelectPet/style.css.ts
  components/Diary/DiaryList/index.tsx
  components/Diary/DiaryList/style.css.ts
  components/Diary/EmptyDiaryList/index.tsx
  components/Diary/EmptyDiaryList/style.ts
  components/Diary/ImageInput/index.tsx
  components/Diary/ImageInput/style.css.ts
  next.config.js
  package-lock.json
  package.json
  public/data/bird-type.json
  public/data/cat-type.json
  public/data/dog-type.json
  public/data/fish-type.json
  public/data/insect-type.json
  public/data/rabbit-type.json
  public/data/rat-type.json
  public/data/reptile-type.json
  public/next.svg
  public/vercel.svg
  states/atom.ts
  styles/global.css.ts
Labels: 💫 feat

#18 [#15] feat : 건강수첩, 에디터 페이지 기능 일부 구현
  app/healthlog/(route)/edit/page.css.ts
  app/healthlog/(route)/edit/page.tsx
  app/healthlog/page.css.ts
  app/healthlog/page.tsx
  components/@common/HealthLogTaskList/HealthLogTaskItem/index.tsx
  components/@common/HealthLogTaskList/HealthLogTaskItem/style.css.ts
  components/@common/HealthLogTaskList/index.tsx
  components/@common/HealthLogTaskList/style.css.ts
  components/EmptyHealthLog/style.css.ts
  components/HealthLogList/HealthLog/index.tsx
  components/HealthLogList/index.tsx
  components/QuickButtons/style.css.ts
  package-lock.json
  package.json
Labels: 💫 feat

#30 [#29] chore : deploy setting
  appspec.yml
  deploy.sh
Labels: 🧹 chore

#23 [#22] feat : 마이 펫 관리하기 카드 컴포넌트 구현, 폴더 구조 변경
  app/(settingsMenu)/ask/page.tsx
  app/(settingsMenu)/faq/page.tsx
  app/(settingsMenu)/myprofile/page.tsx
  app/(settingsMenu)/notice/page.tsx
  app/(settingsMenu)/receivedinvites/page.tsx
  app/globals.css
  app/settings/page.tsx
  assets/edit-petcard.svg
  assets/invite-petcard.svg
  components/MyProfile/index.tsx
  components/MyProfile/mockData.json
  components/MyProfile/style.css.ts
  components/MypetCarousel/Card/index.tsx
  components/MypetCarousel/Card/style.css.ts
  components/MypetCarousel/index.tsx
  components/MypetCarousel/mockdata.json
  styles/global.css.ts
Labels: 💫 feat, 🍀 refactor

#24 [#21] refactor : 로그인 이후 홈 진입까지 관련 페이지 리팩토링
  app/(participateModal)/@modal/(.)participate/page.tsx
  app/create/(route)/petgroup/page.tsx
  app/create/(route)/userprofile/page.tsx
  app/home/page.tsx
  components/@common/HealthLogTaskList/HealthLogTaskItem/index.tsx
  components/HomeHealthLogPreview/HomeHealthLogTaskItem.tsx
  components/HomeHealthLogPreview/HomeHealthLogTaskList.tsx
  components/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/HomePetProfile/HomePetProfile.tsx
  components/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
Labels: 🍀 refactor

#28 [#27] chore : svgr setting
  app/page.tsx
  assets/PlusIcon.tsx
  assets/edit.svg
  next.config.js
  svg.d.ts
Labels: 🧹 chore

#17 [#14] feat: 온보딩 페이지 건너뛰기, 페이지네이션 기능
  app/onboarding/page.css.ts
  app/onboarding/page.tsx
  components/Onboarding/index.tsx
  components/Onboarding/styles.css.ts
  components/Pagination/index.tsx
  components/Pagination/styles.css.ts
  components/commons/buttons/style.css.ts
Labels: 💫 feat

#34 [#33] refactor : 관리 페이지 리팩토링
  components/MypetCarousel/Card/index.tsx
  components/MypetCarousel/index.tsx
  components/MypetCarousel/mockdata.json
  utils/calculateAge.ts
Labels: 💫 feat, 🍀 refactor

#40 [#36] feat : 건강수첩 에디터 페이지 대분류에 따른 입력 항목 세부 기능
  .env
  .eslintrc
  app/healthlog/(route)/edit/page.css.ts
  app/healthlog/(route)/edit/page.tsx
  app/healthlog/page.tsx
  components/@common/LogList/LogItem/index.tsx
  components/@common/LogList/LogItem/style.css.ts
  components/@common/LogList/index.tsx
  components/@common/LogList/style.css.ts
  components/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/SearchLocation/index.tsx
Labels: 💫 feat

#49 [#48] feat : 리액트 Portal 사용하여 모달 리팩토링
  app/layout.tsx
  components/@common/Modal/index.tsx
  hooks/useModal.tsx
Labels: 💫 feat, 🍀 refactor

#45 [#32] feat : 펫그룹 참여 폼 구현
  app/(participateModal)/@modal/(.)participate/page.tsx
  app/(participateModal)/@modal/default.tsx
  app/(participateModal)/layout.tsx
  app/(participateModal)/participate/page.tsx
  app/(participateModal)/select/page.tsx
  app/home/page.tsx
  app/select/page.css.ts
  app/select/page.tsx
  components/Home/HomeHealthLogPreview/HomeHeathLogPreview.tsx
  components/Home/HomePetProfile/HomePetProfile.tsx
  components/Participate/ParticipatePetGroupForm.tsx
  components/Participate/ParticipatePetGroupModal.css.ts
  components/Participate/ParticipatePetGroupModal.tsx
  components/ParticipatePetGroupModal/ParticipatePetGroupModal.css.ts
  components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
  constatnts/inputConstant.ts
Labels: 💫 feat

#41 [#39] feat : 육아일기 작성하기 페이지 및 기능
  app/diary/edit/page.tsx
  app/diary/edit/style.css.ts
  components/Diary/ImageInput/index.tsx
  components/Diary/ImageInput/style.css.ts
  package-lock.json
  package.json
Labels: 💫 feat, 🥹 incomplete

#42 [#38] feat : signin form 구현
  app/login/(route)/email/page.tsx
  app/login/page.tsx
  app/onboarding/page.tsx
  app/signup/(route)/email/page.tsx
  app/signup/page.tsx
  components/@common/SignButton/index.tsx
  components/@common/SignButton/style.css.ts
  components/Sign/AlertModal/index.tsx
  components/Sign/AlertModal/styles.css.ts
  components/Sign/SignForm/SigninForm.tsx
  components/Sign/SignForm/SignupForm.tsx
  components/Sign/SignForm/styles.css.ts
  components/Sign/SignInput/Input.tsx
  components/Sign/SignInput/PasswordInput.tsx
  components/Sign/SignInput/styles.css.ts
  components/Sign/SubmitButton/index.tsx
  components/Sign/SubmitButton/styles.css.ts
Labels: 💫 feat, 🥹 incomplete

#53 [#47] refactor : 건강수첩 에디터 페이지 리팩토링
  app/healthlog/(route)/edit/page.css.ts
  app/healthlog/(route)/edit/page.tsx
  app/healthlog/page.tsx
  components/Healthlog/EmptyHealthLog/index.tsx
  components/Healthlog/EmptyHealthLog/style.css.ts
  components/Healthlog/QuickButtons/index.tsx
  components/Healthlog/QuickButtons/style.css.ts
  components/Healthlog/SearchLocation/index.tsx
  components/Healthlog/SearchLocation/style.css.ts
  components/Healthlog/SubtypeDetail/index.tsx
  components/Healthlog/SubtypeDetail/style.css.ts
  components/Healthlog/VanillaCalendar/index.tsx
  components/SearchLocation/index.tsx
Labels: 💫 feat, 🍀 refactor
