Repository ppp-team/my-pet-log, pull requests merged in 2024-05, with the labels that each got.

#358 [#328] refactor : 대댓글 태그 로직 수정
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/style.css.ts
Labels: 🍀 refactor

#361 [#360] refactor : 일기 middleware, textarea, header
  app/diary/(diary)/my-pet/page.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryDetail/style.css.ts
  app/diary/detail/[id]/page.tsx
  app/diary/select/page.tsx
  app/template.tsx
  middleware.ts
Labels: 🍀 refactor

#363 [#362] fix : 소셜로그인 에러 테스트1
  app/(auth)/_components/SignButton/GoogleButton.tsx
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/page.tsx
  lib/auth.ts
Labels: 🐛 bug

#364 [#362] fix : 소셜로그인 에러 테스트2
  lib/auth.ts
Labels: 🐛 bug

#365 [#362] fix : 소셜로그인 에러 테스트3
  middleware.ts
Labels: 🐛 bug

#366 [#362] fix : 소셜로그인 에러 테스트4
  middleware.ts
Labels: 🐛 bug

#367 [#362] fix : 미들웨어 코드 롤백
  middleware.ts
Labels: 🐛 bug

#369 [#362] chore : NEXT_PUBLIC_ 추가
  lib/auth.ts
Labels: 🧹 chore

#368 [#362] 소셜로그인 에러 테스트5
  app/(auth)/_components/AuthContext.tsx
  app/(auth)/_components/RedirectToHome/index.tsx
  app/(auth)/_components/SignButton/GoogleButton.tsx
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/(auth)/loginflow/page.tsx
  app/(auth)/oauth/callback/[provider]/page.tsx
  app/_constants/oauth.ts
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  lib/auth.ts
  middleware.ts
Labels: 🐛 bug

#371 [#370] refactor : 구글 로그인 버튼 임시 주석처리
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/(auth)/login/page.tsx
Labels: 🍀 refactor

#375 [#373] fix : 초대코드 input 붙여넣기 시 등록 버튼 활성화
  app/home/_components/ParticipatePetGroupModal/ParticipatePetGroupModal.tsx
Labels: 🐛 bug

#376 [#374] Refactor : postPets 실행 완료 후에 handlePath 실행하도록 코드 수정
  app/_components/PetRegister/index.tsx
Labels: 🐛 bug

#378 [#377] fix : 소셜로그인 에러 테스트6 (구글로그인 1)
  app/(auth)/_components/SignButton/GoogleButton.tsx
  app/(auth)/_components/SignButton/KakaoButton.tsx
  app/(auth)/login/page.tsx
  app/(auth)/oauth/callback/[provider]/page.tsx
  app/_constants/oauth.ts
Labels: 🐛 bug

#379 [#298] fix : 동물 관리 시 세팅페이지로
  app/_components/Layout/MobilePetGroupDropdown/MobilePetGroupDropdown.tsx
Labels: 🛠️ fix

#380 [#377] fix : 소셜로그인 에러 테스트7 (디버깅용 콘솔로그 삭제)
  app/(auth)/oauth/callback/[provider]/page.tsx
Labels: 🐛 bug

#381 [#298] fix : 피드 콘솔 에러 수정
  app/diary/_components/Feed/NoMedia/index.tsx
  app/diary/_components/Feed/index.tsx
Labels: 🛠️ fix

#387 [#298] fix : 없는 사용자 초대 시 에러메시지
  app/settings/_components/InvitationForm/index.tsx
Labels: 🛠️ fix

#386 UI : 답글, 좋아요 버튼 사이 간격 조정
  app/diary/_components/DiaryDetail/Comment/index.tsx
Labels: 🎨 UI

#383 [#382] fix : accessToken 만료시 동작 수정
  app/_api/auth/index.ts
  app/_api/axios.ts
  app/_api/pets/index.ts
  app/access-expired/loading.tsx
  app/access-expired/logout.tsx
  app/access-expired/page.tsx
  app/access-expired/style.css.ts
  app/error.tsx
  middleware.ts
Labels: 🛠️ fix

#385 [#384] fix: diary detail 하단 GNB 보이도록 수정
  app/diary/(diary)/my-pet/style.css.ts
  app/diary/_components/DiaryDetail/style.css.ts
  app/diary/_components/Input/VideoInput/index.tsx
  app/template.tsx
Labels: 🛠️ fix

#388 fix : warning
  app/(auth)/_components/SignForm/SigninForm.tsx
  app/(auth)/_components/SignForm/SignupForm.tsx
  app/(auth)/_components/SignInput/Input.tsx
  app/(auth)/login/(route)/email/page.tsx
Labels: 🛠️ fix

#390 fix : no-pet-group gnb
  app/(first-time-use)/no-pet-group/page.css.ts
  app/template.tsx
Labels: 🛠️ fix

#392 [#391] Feat : 소셜로그인을 구분하는 loginType 추가에 따른 로직 수정
  app/(auth)/oauth/callback/[provider]/page.tsx
  app/_api/auth/index.ts
  app/_components/Toast/style.css.ts
  app/_types/user/types.ts
  app/settings/(account)/layout.tsx
Labels: 💫 feat

#402 [#401] QA Fix : 동물 등록 컴포넌트 QA수정
  app/_components/PetRegister/index.tsx
  app/settings/_components/EditPetRegisterForm/index.tsx
Labels: 🛠️ fix

#403 [#401] QA fix : postPet 성공시 Modal 알맞게 뜨도록 수정
  app/_components/PetRegister/index.tsx
Labels: 🐛 bug

#413 Fix : 동물 등록 무한루프 에러 수정
  app/_components/PetRegister/index.tsx
Labels: 🛠️ fix
