Repository ppp-team/my-pet-log, pull requests merged in 2024-03, with the labels that each got.

#279 [#257] refactor : 건강수첩 추가 리팩토링
  app/_components/DateInput/index.tsx
  app/healthlog/_components/LogWriteButton/index.tsx
  app/healthlog/_components/LogWriteButton/style.css.ts
  app/healthlog/page.tsx
  styles/zindex.css.ts
Labels: 🍀 refactor

#283 [#282] fix : 비밀번호 페이지 로딩 시 1초동안 css 안먹힘 이슈
  app/settings/(account)/password/loading.tsx
  app/settings/(account)/profile/loading.tsx
  app/settings/(petmate)/invitation/loading.tsx
  app/settings/(petmate)/member/loading.tsx
Labels: 🛠️ fix

#284 [#281] refactor : 폰트 최적화 개선
  app/layout.tsx
  app/settings/(account)/profile/page.css.ts
  app/settings/_components/InviteModal/style.css.ts
  fonts/layout.tsx
  styles/PretendardVariable.woff2
  styles/fonts.ts
  styles/global.css.ts
Labels: 🍀 refactor

#286 [#285] feat : 마이펫 일기, 친구의 일기 경로 변경한 후 나누기
  app/_components/Layout/MobileFooterNavigationBar/MobileFooterNavigationBar.tsx
  app/_components/Layout/PcHeaderNav/PcHeaderNav.tsx
  app/_constants/pagesWithHeader.ts
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/layout.css.ts
  app/diary/(diary)/layout.tsx
  app/diary/(diary)/my-pet/constant.ts
  app/diary/(diary)/my-pet/loading.tsx
  app/diary/(diary)/my-pet/page.tsx
  app/diary/(diary)/my-pet/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryList/index.tsx
  app/diary/_components/Form/CreateForm/index.tsx
  app/diary/create/page.tsx
  app/diary/detail/[id]/page.tsx
  app/diary/edit/[id]/page.tsx
  app/diary/search/page.tsx
  app/diary/select/page.tsx
  app/sitemap.ts
  middleware.ts
Labels: 💫 feat

#290 [#287] feat : 구독중인 펫계정 레이아웃
  app/(auth)/loginflow/page.tsx
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/SubscriptionList/index.tsx
  app/settings/_components/SubscriptionList/style.css.ts
  app/settings/page.tsx
  app/settings/subscriptions/page.tsx
  app/template.tsx
  public/icons/subscription-box.svg
Labels: 💫 feat

#291 [#288, #289] feat : 마이펫 캐러셀, 구독자 관리페이지 레이아웃
  app/_constants/pagesWithHeader.ts
  app/settings/(pet-subscriber)/blocked-user/page.tsx
  app/settings/(pet-subscriber)/layout.css.ts
  app/settings/(pet-subscriber)/layout.tsx
  app/settings/(pet-subscriber)/style.css.ts
  app/settings/(pet-subscriber)/subscriber/page.tsx
  app/settings/_components/MyPetInfo/index.tsx
  app/settings/_components/MyPetInfo/style.css.ts
  app/settings/_components/MypetCarousel/index.tsx
  app/settings/_components/MypetCarousel/styles.css.ts
  public/icons/edit-petcard.svg
Labels: 💫 feat

#293 [#292] feat : 알림센터 UI
  app/_components/BackHeader/index.tsx
  app/_components/BackHeader/style.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.css.ts
  app/_components/Layout/MobileHeaderPetGroup/MobileHeaderPetGroup.tsx
  app/notification/_components/HasNotification/HasNotification.css.ts
  app/notification/_components/HasNotification/HasNotification.tsx
  app/notification/_components/NoNotification/NoNotification.css.ts
  app/notification/_components/NoNotification/NoNotification.tsx
  app/notification/_components/Notification/Notification.css.ts
  app/notification/_components/Notification/Notification.tsx
  app/notification/layout.css.ts
  app/notification/layout.tsx
  app/notification/page.tsx
  public/icons/arrow-up.svg
  public/icons/notification.svg
  public/images/no-notification.svg
Labels: 🎨 UI

#297 [#296] feat : 대댓글 컴포넌트
  app/diary/_components/DiaryDetail/ReplyComment/index.tsx
  app/diary/_components/DiaryDetail/ReplyComment/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/healthlog/_components/CreateForm/style.css.ts
  app/healthlog/_components/EditForm/style.css.ts
  app/healthlog/_components/HealthlogContent/style.css.ts
Labels: 💫 feat

#299 Feat/friend pet page layout
  app/_constants/pagesWithHeader.ts
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/friend-pet/style.css.ts
Labels: 🎨 UI

#301 [#298] feat : 친구의 일기 이미지 슬라이드 구현
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/friend-pet/style.css.ts
  app/diary/(diary)/friend-pet/swiper.css
Labels: 💫 feat

#303 [#302] feat : 대댓글 api 연동
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/Comment/style.css.ts
  app/diary/_components/DiaryDetail/ReComment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/style.css.ts
  app/diary/_components/DiaryDetail/ReplyComment/index.tsx
  app/diary/_components/DiaryDetail/ReplyComment/style.css.ts
  app/diary/_components/DiaryDetail/index.tsx
  app/diary/_components/DiaryDetail/style.css.ts
Labels: 💫 feat

#305 [#304] feat : 구독중인 펫계정 api 연동
  app/_api/subscription/index.ts
  app/_types/subscriptions/types.ts
  app/settings/_components/EmptySubscribedPet/index.tsx
  app/settings/_components/EmptySubscribedPet/style.css.ts
  app/settings/_components/SubscriptionList/index.tsx
  public/icons/empty-box.svg
Labels: 💫 feat

#306 [#300] pet이름 중복검사 기능, 리팩토링
  app/_api/pets/index.ts
  app/_components/PetRegister/component/OptionalCheck/index.tsx
  app/_components/PetRegister/component/PetWeightInput.tsx
  app/_components/PetRegister/component/PetdateInput/index.tsx
  app/_components/PetRegister/component/RadioInput/GenderRadio.tsx
  app/_components/PetRegister/component/RadioInput/NeuteringRadio.tsx
  app/_components/PetRegister/component/RadioInput/style.css.ts
  app/_components/PetRegister/index.tsx
  app/_components/PetRegister/style.css.ts
  app/_constants/inputConstant.ts
  app/_types/petGroup/types.ts
  app/settings/_components/EditPetRegisterForm/index.tsx
  app/settings/_components/EditPetRegisterForm/style.css.ts
Labels: 💫 feat, 🍀 refactor

#309 [#308] refactor : 검색 키워드 api 연동
  app/_api/diary/index.ts
  app/diary/(diary)/my-pet/constant.ts
  app/diary/search/page.tsx
Labels: 🍀 refactor

#310 [#298] feat : 좋아요, 댓글, 더보기 레이아웃
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/friend-pet/style.css.ts
  public/icons/chat.svg
  public/icons/hearticon.svg
Labels: 💫 feat, 🎨 UI

#311 [#302] feat : 대댓글 api 연동
  app/_api/diary/index.ts
  app/_types/diary/type.ts
  app/diary/_components/DiaryDetail/Comment/index.tsx
  app/diary/_components/DiaryDetail/ReComment/index.tsx
Labels: 💫 feat

#312 [#298] feat : 댓글창 열기 구현
  app/diary/(diary)/friend-pet/page.tsx
  app/diary/(diary)/friend-pet/style.css.ts
  app/diary/_components/CommentModalContainer/index.tsx
  app/diary/_components/CommentModalContainer/style.css.ts
  public/icons/chat-icon.svg
  public/icons/chat.svg
  public/icons/heart-icon.svg
Labels: 💫 feat
